### ISSUE TITLE
_dot_

### ISSUE THREAD

**Issue by errogaht** [php-enqueue/sqs#1]
hello! Thanks but guys you have poor documentation. It's very hard to me to start using your libs. Well documented PHP projects have WORKING examples, your examples are not working.
I just trying to send a message to the client, I look into your doc of SQS and found configuration reference. The result I got https://goo.gl/1EmZgN WTF is _dot_ ? I don't need this MAGIC. a need queue name '1.fifo' why I can't use it? please provide working step by step examples. I go through many doc pages you created and don't understand anything.

**Comment by makasim** [comment]
> a need queue name '1.fifo' why I can't use it? 

sorry you can do it, ask Amazon why. 
btw Enqueue Client does not support fifo.
