### ISSUE TITLE
SqsException: Error executing "SendMessage"

### ISSUE THREAD

**Issue by errogaht** [php-enqueue/sqs#2]
Error executing "SendMessage" on "https://sqs.eu-west-1.amazonaws.com/123/1.fifo"; AWS HTTP error: Client error: `POST https://sqs.eu-west-1.amazonaws.com/123/1.fifo` resulted in a `400 Bad Request` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>M (truncated...)
MissingParameter (client): The request must contain the parameter MessageGroupId. - <?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>MissingParameter</Code><Message>The request must contain the parameter MessageGroupId.</Message><Detail/></Error><RequestId>e8987d80-e32e-51a1-9253-2f4f1dcb4910</RequestId></ErrorResponse>

nothing working!!
I just get example from https://github.com/php-enqueue/enqueue-dev/blob/master/docs/bundle/message_producer.md https://goo.gl/md2BgJ

**Comment by makasim** [comment]
The code is widely used in a production by many people, there are functional tests too.

Please stop opening issues. We provide paid support. Send me a mail and discuss the details.
